<?php
$url = 'https://vnexpress.net/rss/kinh-doanh.rss';
$json = file_get_contents("https://api.rss2json.com/v1/api.json?rss_url=".$url);
$data = json_decode($json, true);
?>

<marquee id="news" direction="up">
	<table class="table">
		<tbody>
			<?php foreach ($data['items'] as $k => $new): ?>
			<tr>
				<th>
					<a href="<?= $new['link'] ?>" style="color:blue">
						<?= $new['title'] ?> <br>
						</h5>
							<p style="color:black; font-weight:normal;"><?= strip_tags($new['description']) ?></p>
						</h5>
					</a>
				</th>
				<td>
					<a href="<?= $new['link'] ?>">
						<img data-src="<?= $new['thumbnail'] ?>" 
						style="width: 100%; height: auto;" src="<?= $new['thumbnail'] ?>" data-holder-rendered="true">
					</a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</marquee>

<style>
	#news {
		border: green 0px SOLID;
    font-size: 17px;
		font-family: Arial, Helvetica, sans-serif;
		height: 200px;
		width: 50%;
		float: right;
		display: inline;
		background-color: cornsilk;
	}

	table th {
		/* text-align: right; */
	}

	table td {
		width: 30%;
	}
</style>