FROM php:7.3-fpm

RUN composer self-update --1
WORKDIR /
# RUN chown -R $USER:$USER /var/www/html/aglcomputer/
# RUN chmod -R 777 /var/www/html/aglcomputer/
# RUN sh -c "echo '127.0.0.1 aglcomputer.store' >> /etc/hosts"
