<?php
$arrContextOptions=array(
	"ssl"=>array(
			"verify_peer"=>false,
			"verify_peer_name"=>false,
	),
);

$url = 'https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68';
$data = file_get_contents($url,false, stream_context_create($arrContextOptions));
$data = simplexml_load_string($data);
$data = json_encode($data);
$data = json_decode($data, true);
$last = array_values(array_slice($data['Exrate'], -1))[0];
?>

<span>
	<marquee id="exchange-rate">
		Tỷ giá tiền tệ so với VNĐ: &nbsp;&nbsp;
		<?php foreach ($data['Exrate'] as $k => $currency): ?>
			<?php if ($currency['@attributes']['Buy'] != '-' || $currency['@attributes']['Transfer'] != '-' || $currency['@attributes']['Sell'] != '-'): ?>
				<span style="color:black"><b><?= $currency['@attributes']['CurrencyName'] ?>:</b></span> &nbsp;
				<?php if ($currency['@attributes']['Buy'] != '-'): ?>
					<span style="color:green">Mua</span> <?= $currency['@attributes']['Buy'] ?> &nbsp;
				<?php endif; ?>
				<?php if ($currency['@attributes']['Transfer'] != '-'): ?>
					<span style="color:orange">Chuyển</span> <?= $currency['@attributes']['Transfer'] ?> &nbsp;
				<?php endif; ?>
				<?php if ($currency['@attributes']['Sell'] != '-'): ?>
					<span style="color:red">Bán</span> <?= $currency['@attributes']['Sell'] ?> &nbsp;
				<?php endif; ?>
				<?php if ($currency['@attributes']['CurrencyCode'] != $last['@attributes']['CurrencyCode']): ?>
					&nbsp; --- &nbsp;&nbsp;&nbsp;
				<?php endif; ?>
			<?php endif; ?>
		<?php endforeach; ?>
	</marquee>
</span>

<style>
	marquee {
		border: green 3px SOLID;
    font-size: 17px;
		font-family: Arial, Helvetica, sans-serif;
	}
</style>